### ISSUE TITLE
As a user, so that I can ‘promote’ an article, I want to be able to vote on a statement.(2)

### ISSUE THREAD

**Issue by ChrisKummelstedt** [ChrisKummelstedt/LyRRiC#5]

**Comment by RichardWatkins1** [comment]
make vote class
and the corresponding model

**Comment by RichardWatkins1** [comment]
make vote model associations with statements

**Comment by RichardWatkins1** [comment]
make vote association with users

**Comment by RichardWatkins1** [comment]
create vote method against a statement - 
-update the verdict in the vote class  
- record the vote against the user
-record the vote against the statement

**Comment by RichardWatkins1** [comment]
Add controller and test

**Comment by RichardWatkins1** [comment]
create view and tests to display statements and vote button/swipe option.
